version: '3.7'

services:

  api:
    build: 
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - postgis

  # scrapper:
  #   build: 
  #     context: ./scrapper
  #   ports: 
  #     - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4040:4040"

  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5