version: '3.7'

services:

  server:
    image: nginx:latest
    volumes:
      - "./config/sites-available:/etc/nginx/sites-available"
      - "./config/sites-enabled:/etc/nginx/sites-enabled"

  api:
    build: 
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - postgis
    command: "gunicorn -b :5000 --access-logfile - --error-logfile - main:app"
    environment:
      - DB_USER=dbinstance_dev
      - DB_PASSWORD=WebWizard#1
      - DB_PORT=5432
  
  scrapper:
    build: 
      context: ./scrapper
    ports: 
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        API_SERVER: api:5000
    ports:
      - "4040:4040"